version: "3"
services:
  dytt8:
    build: .
    container_name: fin
    logging: 
      options: 
        max-size: "10m"
    volumes: 
      - /www/fin:/app/fin
    working_dir: /app/fin
    environment: 
      - FIN_SMTP_PWD=${SMTP_PWD}
      - FIN_DINGTALK_TOKEN=${DINGTALK_TOKEN}
      - FIN_DINGTALK_SECRET=${DINGTALK_SECRET}
      - FIN_DB_HOST=${PGSQL_HOST}
      - FIN_DB_USER=${PGSQL_USER}
      - FIN_DB_DB=${PGSQL_DB}
      - FIN_DB_PWD=${PGSQL_PWD}
    networks:
      - fin
    command: pip install -U akshare && python tasks.py

networks: 
  fin: